# This dockerfile must be built with the monorepo root directory as cwd
FROM node:lts-alpine

ARG PUBLIC_API_URL
ARG PUBLIC_WS_URL

WORKDIR /app

#all folders needed for the build
COPY front/package.json front/package-lock.json front/.

WORKDIR /app/front

RUN bun install

COPY front /app/front
COPY domain /app/domain

RUN npm run build

ENV PORT=3002
EXPOSE 3002

CMD ["node", "build/index.js"]
