# This dockerfile must be built with the monorepo root directory as cwd
FROM node:lts-alpine

WORKDIR /app

#all folders needed for the build
COPY front/package.json front/package-lock.json front/.

WORKDIR /app/front

RUN npm i

COPY front /app/front
COPY domain /app/domain

RUN npm run build

ENV PORT=5173
EXPOSE 5173

CMD ["node", "build/index.js"]
