version: "3.8"

services:
  backend:
    image: oven/bun:latest
    working_dir: /app/back
    volumes:
      - .:/app
    command: bun run compose
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: arm64v8/node:latest
    working_dir: /app/front
    volumes:
      - .:/app
    command: npm run compose
    ports:
      - "5173:5173"

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: microretro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
