

































return BoardStep.DONE;    case BoardStep.DONE: return BoardStep.DONE;    case BoardStep.DISCUSS: return BoardStep.DISCUSS;    case BoardStep.VOTE: return BoardStep.VOTE;    case BoardStep.PRESENT: return BoardStep.PRESENT;    case BoardStep.WRITE: switch (current) {export function getNextState(current: BoardStep): BoardStep { } DONE = "done", DISCUSS = "discuss", VOTE = "vote", PRESENT = "present", WRITE = "write",export enum BoardStep { } summary ?: string; step: BoardStep; users: User[]; cards: Card[]; createdAt: Date; id: BoardId; export interface Board {export type BoardId = string; import type { User } from "./user"; import type { Card } from "./card";